### ISSUE TITLE
Question: will my commit disappear after this repository deleted?

### ISSUE THREAD

**Issue by jenna1k** [CodeForWomen/github-seminar#34]

**Comment by jenna1k** [comment]
[Github Help](https://help.github.com/) 페이지에서 관련 사항을 찾아봤습니다.

> *[Deleting a public repository](https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/)*
When you delete a public repository, one of the existing public forks is chosen to be the new parent repository. All other repositories are forked off of this new parent and subsequent pull requests go to this new parent.

존재하는 public forks 중 하나가 새로운 parent repository 가 되나보네요!

[commits](https://help.github.com/categories/commits/)에 대해서는 정확하게 이해가 안되는데 찬찬히 살펴봐야겠어요.

github를 이용할때 command line 으로 [git](https://git-scm.com/)을 사용할 줄 알아야하나봐요.
[git 사용법](https://git-scm.com/doc)을 찾아봤는데 [한국어](https://git-scm.com/book/ko/v2)로도 번역된 자료가 있네요 :smile:

**Comment by sujinleeme** [comment]
@jenna1k  스스로 잘 터득하셨네요!
세미나 때에는 커맨드라인으로 깃을 사용하지 않았었죠?
[sourcetree](https://www.sourcetreeapp.com/)도 한번 보시면 도움이 되실 거에요.  좀더 시각적으로 브랜치와 커밋 로그를 확인할 수 있어요.
